"""Shell tab-completion scripts for bash, zsh and fish.

The scripts are rendered from string templates (pure shell, zero deps) and cover
every sub-command plus a dynamic ``<session_id>`` completion that reads ids from
``claudestudio list --json``.
"""

from __future__ import annotations

import os

# Every top-level sub-command ClaudeStudio exposes (v0.7.0).
COMMANDS: list[str] = [
    "index", "serve", "list", "search", "ask", "wrapped", "export", "report",
    "watch", "budget", "generate-claude-md", "mcp", "info", "stats", "demo",
    "doctor", "hook", "tag", "narrative", "digest", "share", "benchmark",
    "resume", "open", "compare", "verify-claude-md", "webhook", "tour", "plugins",
    "search-history", "github-summary", "template",
    # v0.7.0 Intelligence Layer
    "ai-summary", "ai-coach", "ai-prompt", "similar", "clusters", "watch-session",
    "context-analysis", "model-stats", "annotations", "completions",
]

_CMDS = " ".join(COMMANDS)


def bash_script() -> str:
    return f"""# bash completion for claudestudio — `source` this file or drop it in
# ~/.bash_completion.d/.  Generated by `claudestudio completions bash`.
_claudestudio_ids() {{
    # dynamic <session_id> completion: first 200 ids, kept fast
    claudestudio list --json 2>/dev/null | python3 -c \\
"import sys,json
try:
    rows=json.load(sys.stdin)
    print(' '.join(r.get('id','') for r in rows[:200]))
except Exception:
    pass"
}}

_claudestudio() {{
    local cur prev cmds
    COMPREPLY=()
    cur="${{COMP_WORDS[COMP_CWORD]}}"
    prev="${{COMP_WORDS[COMP_CWORD-1]}}"
    cmds="{_CMDS}"
    if [ "$COMP_CWORD" -eq 1 ]; then
        COMPREPLY=( $(compgen -W "$cmds" -- "$cur") )
        return 0
    fi
    case "$prev" in
        ai-summary|similar|clusters|narrative|resume|open|export|context-analysis|watch-session)
            COMPREPLY=( $(compgen -W "$(_claudestudio_ids)" -- "$cur") )
            return 0 ;;
    esac
    COMPREPLY=( $(compgen -W "--last --json --help --db --root" -- "$cur") )
    return 0
}}
complete -F _claudestudio claudestudio
complete -F _claudestudio cs
"""


def zsh_script() -> str:
    return f"""#compdef claudestudio cs
# zsh completion for claudestudio — install into a directory on your $fpath.
# Generated by `claudestudio completions zsh`.
_claudestudio() {{
    local -a cmds
    cmds=({_CMDS})
    if (( CURRENT == 2 )); then
        _describe 'command' cmds
        return
    fi
    case "${{words[2]}}" in
        ai-summary|similar|clusters|narrative|resume|open|export|context-analysis|watch-session)
            local -a ids
            ids=(${{(f)"$(claudestudio list --json 2>/dev/null | python3 -c \\
'import sys,json;
try:
 rows=json.load(sys.stdin); print(chr(10).join(r.get(\\"id\\",\\"\\") for r in rows[:200]))
except Exception: pass')"}})
            _describe 'session' ids ;;
        *)
            _arguments '--last' '--json' '--help' '--db=' '--root=' ;;
    esac
}}
compdef _claudestudio claudestudio cs
"""


def fish_script() -> str:
    lines = [
        "# fish completion for claudestudio.",
        "# Generated by `claudestudio completions fish`.",
        "function __claudestudio_ids",
        "    claudestudio list --json 2>/dev/null | python3 -c \"import sys,json\\n"
        "try:\\n rows=json.load(sys.stdin); print(chr(10).join(r.get('id','') "
        "for r in rows[:200]))\\nexcept Exception: pass\"",
        "end",
        "complete -c claudestudio -f",
    ]
    for cmd in COMMANDS:
        lines.append(
            f"complete -c claudestudio -n '__fish_use_subcommand' -a '{cmd}'")
    for cmd in ("ai-summary", "similar", "clusters", "narrative", "resume", "open",
                "context-analysis", "watch-session"):
        lines.append(
            f"complete -c claudestudio -n '__fish_seen_subcommand_from {cmd}' "
            "-a '(__claudestudio_ids)'")
    lines.append("complete -c claudestudio -l last -d 'use the most recent session'")
    lines.append("complete -c claudestudio -l json -d 'machine-readable output'")
    return "\n".join(lines) + "\n"


def render(shell: str) -> str:
    shell = (shell or "").lower()
    if shell == "bash":
        return bash_script()
    if shell == "zsh":
        return zsh_script()
    if shell == "fish":
        return fish_script()
    raise ValueError(f"unsupported shell {shell!r} (choose bash, zsh or fish)")


def detect_shell() -> str:
    base = os.path.basename(os.environ.get("SHELL", "")).lower()
    for cand in ("bash", "zsh", "fish"):
        if cand in base:
            return cand
    return "bash"


def _default_path(shell: str, root: str) -> str:
    if shell == "bash":
        return os.path.join(root, ".bash_completion.d", "claudestudio")
    if shell == "zsh":
        return os.path.join(root, ".zsh", "completions", "_claudestudio")
    return os.path.join(root, ".config", "fish", "completions", "claudestudio.fish")


def install(shell: str | None = None, *, root: str | None = None) -> dict:
    """Render and write the completion file for ``shell`` (auto-detected if None)."""
    shell = (shell or detect_shell()).lower()
    script = render(shell)
    root = root or os.path.expanduser("~")
    path = _default_path(shell, root)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(script)
    return {"shell": shell, "path": path, "bytes": len(script.encode("utf-8"))}


# ---------------------------------------------------------------------------
# self-test
# ---------------------------------------------------------------------------

def selftest(c) -> None:
    import tempfile

    b, z, f = bash_script(), zsh_script(), fish_script()
    c.ok("complete -F _claudestudio claudestudio" in b,
         "bash script registers the completion function")
    c.ok(z.startswith("#compdef claudestudio") or "#compdef claudestudio" in z,
         "zsh script declares #compdef claudestudio")
    c.ok("complete -c claudestudio" in f, "fish script uses complete -c claudestudio")

    c.eq(render("bash"), b, "render(bash) dispatches to bash_script")
    c.eq(render("zsh"), z, "render(zsh) dispatches to zsh_script")
    c.eq(render("fish"), f, "render(fish) dispatches to fish_script")
    c.eq(render("BASH"), b, "render is case-insensitive")
    try:
        render("powershell")
        c.ok(False, "render(unknown) should raise")
    except ValueError:
        c.ok(True, "render(unknown shell) raises ValueError")

    for cmd in ("ai-summary", "similar", "clusters", "completions", "model-stats",
                "annotations", "context-analysis", "watch-session", "ai-coach", "ai-prompt"):
        c.ok(cmd in COMMANDS, f"COMMANDS includes {cmd}")
    c.ok(len(COMMANDS) >= 35, "COMMANDS covers the full surface")
    # each script mentions several commands
    c.ok(sum(1 for cmd in COMMANDS if cmd in b) >= 10, "bash script lists many commands")
    c.ok(sum(1 for cmd in COMMANDS if cmd in z) >= 10, "zsh script lists many commands")
    c.ok(sum(1 for cmd in COMMANDS if cmd in f) >= 10, "fish script lists many commands")

    c.ok(detect_shell() in ("bash", "zsh", "fish"), "detect_shell returns a known shell")

    with tempfile.TemporaryDirectory() as tmp:
        for shell in ("bash", "zsh", "fish"):
            info = install(shell, root=tmp)
            c.eq(info["shell"], shell, f"install reports shell {shell}")
            c.ok(os.path.exists(info["path"]), f"install writes a file for {shell}")
            c.ok(info["bytes"] > 0, f"install file for {shell} is non-empty")
            with open(info["path"], encoding="utf-8") as fh:
                c.eq(fh.read(), render(shell), f"installed {shell} file equals render()")
